# Generated by Django 5.0.3 on 2024-03-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Tomografia', 'Tomografia')], default='Tomografia', max_length=50)),
                ('data_hora', models.DateTimeField()),
                ('tecnico', models.CharField(max_length=100)),
                ('laudo', models.TextField()),
                ('imagem_exame', models.ImageField(upload_to='imagens_exames/')),
            ],
        ),
    ]
