# Generated by Django 5.0.3 on 2024-03-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomografo_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exame',
            name='imagem_exame',
            field=models.CharField(max_length=200),
        ),
    ]
