# Generated by Django 5.0.3 on 2024-03-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomografo_api', '0002_alter_exame_imagem_exame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exame',
            name='data_hora',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
