# Generated by Django 5.0.3 on 2024-03-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomografo_api', '0003_alter_exame_data_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exame',
            name='imagem_exame',
            field=models.FileField(upload_to='imagens_exames/'),
        ),
    ]
